# 1. Compare version of recipe with latest release
# 2. If version is newer than latest release, bump the version
# 3. Download assets, get SHA256, update SH256 in recipe
# 4. Checkout branch, reset to master (or use non-master branch synced without the workflow)
# 5. Add and commit recipe to repo
# 6. Create PR to bioconda

name: "Create clean branch"

on:
  workflow_dispatch: # click the button on Github repo!

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
      # REQUIRED step
      # Step 1: run a standard checkout action, provided by github
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - run: python scripts/autobumper.py
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote add upstream https://github.com/bioconda/bioconda-recipes
          git fetch upstream
          git checkout -b update/test
          git reset --soft upstream/master
          git add version.txt
          git commit -m "Test"
          git push -u origin update/test

# - run: |
# git config user.name github-actions
# git config user.email github-actions@github.com
# git remote add upstream https://github.com/bioconda/bioconda-recipes
# git fetch upstream
# git checkout -b update/test
# git reset --hard upstream/master
